name       : libatk
version    : 2.34.1
release    : 23
source     :
    - https://download.gnome.org/sources/atk/2.34/atk-2.34.1.tar.xz : d4f0e3b3d21265fcf2bc371e117da51c42ede1a71f6db1c834e6976bb20997cb
license    : GPL-3.0-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
builddeps  :
    - pkgconfig32(gobject-2.0)
    - gtk-doc
emul32     : yes
replaces   :
    - atk
    - devel : atk-devel
    - docs : atk-docs
setup      : |
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
