name       : libatk
version    : 2.26.0
release    : 18
source     :
    - https://download.gnome.org/sources/atk/2.26/atk-2.26.0.tar.xz : eafe49d5c4546cb723ec98053290d7e0b8d85b3fdb123938213acb7bb4178827
license    : GPL-3.0
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
replaces   :
    - atk
    - devel : atk-devel
    - docs : atk-docs
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
