name       : libatk
version    : 2.32.0
release    : 21
source     :
    - https://download.gnome.org/sources/atk/2.32/atk-2.32.0.tar.xz : cb41feda7fe4ef0daa024471438ea0219592baf7c291347e5a858bb64e4091cc
license    : GPL-3.0-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
builddeps  :
    - pkgconfig32(gobject-2.0)
    - gtk-doc
emul32     : yes
replaces   :
    - atk
    - devel : atk-devel
    - docs : atk-docs
setup      : |
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
